
# VERSIÓN LIMPIA Y CORRECTA

[versions]
# Herramientas de compilación
agp = "8.5.1"
kotlin = "1.9.23"
googleGmsPlugin = "4.4.2"

# Librerías de AndroidX (Sistema de Vistas Tradicional)
coreKtx = "1.13.1" # Versión actualizada y compatible
appcompat = "1.7.0" # Versión actualizada y compatible
material = "1.12.0" # Versión actualizada y compatible
activity = "1.8.2"  # Versión clave para compatibilidad con Firebase
constraintlayout = "2.1.4" # Versión estándar

# Librerías de Testing
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

# Firebase
firebaseBom = "33.1.2"
tensorflowLiteSupport = "0.5.0"
tensorflowLiteMetadata = "0.2.0"


[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
tensorflow-lite-metadata = { group = "org.tensorflow", name = "tensorflow-lite-metadata", version.ref = "tensorflowLiteMetadata" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleGmsGoogleServices = { id = "com.google.gms.google-services", version.ref = "googleGmsPlugin" }
